### ISSUE TITLE
Why not reject the error?

### ISSUE THREAD

**Issue by blade254353074** [0x00A/asde#2]

**Comment by blade254353074** [comment]
```javascript
const asde = require('asde')
const fs = require('fs')

const stat = asde(fs.stat)

async function main () {
  try {
    const value = await stat('./file')
    console.log(value)
  } catch (err) {
    console.error(err)
  }
}

main()
```

**Comment by heapwolf** [comment]
👍 A lot of people *love* try/catch! You could easily fork this and make that an option :)

**Comment by heapwolf** [comment]
Also, another idea would be, it could throw via config `const stat = asde(fs.stat, true)`

**Comment by blade254353074** [comment]
All right～

**Comment by heapwolf** [comment]
We could also do a variation like `const stat = asde.throws(fs.stat)`

**Comment by blade254353074** [comment]
Via config will be better.
Most people (I think) will love to see that in try catch partten.
